### ISSUE TITLE
If a serial port is found but it's not a HES controller, the driver appears to get stuck on the handshake

### ISSUE THREAD

**Issue by ric2b** [Jguer/go-hes#2]
<img width="460" alt="capture" src="https://cloud.githubusercontent.com/assets/8846579/20640746/263cb706-b3df-11e6-86c2-20e7e5768f90.PNG">

**Comment by Jguer** [comment]
Issue fixed as of commit [3c9f8cbc02dbef79d05c1bb91bc34b6997b4769f](https://github.com/Jguer/go-hes/commit/3c9f8cbc02dbef79d05c1bb91bc34b6997b4769f).

Windows was unable to read serial properly without going explicit on the options.
```
	mode := &s.Mode{
		BaudRate: 9600,
		Parity:   s.NoParity,
		DataBits: 8,
		StopBits: s.OneStopBit,
	}
```
